# Generated by Django 4.2.8 on 2024-12-29 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_user_following_user_followings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="자기소개"),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="생년월일"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "남성"), ("F", "여성"), ("O", "기타")],
                max_length=10,
                null=True,
                verbose_name="성별",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="", max_length=100, verbose_name="이름"),
        ),
    ]
