# Generated by Django 4.2.8 on 2024-12-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_bio_user_birth_date_user_gender_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=100, unique=True, verbose_name="닉네임"),
        ),
    ]
