# Generated by Django 4.2.8 on 2024-12-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(
                default="product_images/default.jpg", upload_to="product_images/"
            ),
        ),
    ]
